title: Fat Octopus Apps                                                                                                                                                            
  description: "Family-friendly iOS apps"                      
                                                                                                                                                                                     
  defaults:                                                    
    - scope:
        path: ""
      values:
        layout: "default"
